name: ci

on: [pull_request, push]

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: make

      - name: run
        run: ./bin/can -V
